modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/davidjjung/milkyway/issues"
license = "MIT License"

[[mods]]
modId = "milky_way"
version = "${file.jarVersion}"
logoFile = "logo.png"
itemIcon = "minecraft:milk_bucket"
configBackground = "minecraft:textures/block/dirt.png"
authors = "DavigJ"
credits = "DavigJ"
displayURL = "https://modrinth.com/mod/milky-way"
displayName = "Milky Way"
description = '''
    Milking mobs with a configurable cooldown.
    '''

[[dependencies.milky_way]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.milky_way]]
modId = "forge"
mandatory = true
versionRange = "[47.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.milky_way]]
modId = "blueprint"
mandatory = true
versionRange = "[7.0.0,)"
ordering = "AFTER"
side = "BOTH"